# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: backlog

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: backlog
    main: ./cmd/backlog
    binary: backlog
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/alexbrand/backlog/internal/cli.Version={{.Version}}
      - -X github.com/alexbrand/backlog/internal/cli.GitCommit={{.Commit}}
      - -X github.com/alexbrand/backlog/internal/cli.BuildDate={{.Date}}

archives:
  - id: default
    formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: alexbrand
    name: backlog
  draft: false
  prerelease: auto
  mode: replace
  name_template: "Release {{.Tag}}"
