package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new backlog in the current directory",
	Long: `Initialize a new backlog in the current directory by creating the
.backlog/ directory structure with all required status directories.

This command creates:
  .backlog/           - Root backlog directory
  .backlog/backlog/   - Tasks in backlog status
  .backlog/todo/      - Tasks ready to work on
  .backlog/in-progress/ - Tasks currently being worked on
  .backlog/review/    - Tasks in review
  .backlog/done/      - Completed tasks
  .backlog/.locks/    - Lock files for agent coordination
  .backlog/config.yaml - Local configuration file`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runInit()
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit() error {
	backlogDir := ".backlog"

	// Check if .backlog already exists
	if _, err := os.Stat(backlogDir); err == nil {
		return fmt.Errorf("%s already exists", backlogDir)
	}

	// Status directories to create
	statusDirs := []string{
		"backlog",
		"todo",
		"in-progress",
		"review",
		"done",
	}

	// Create status directories
	for _, dir := range statusDirs {
		path := filepath.Join(backlogDir, dir)
		if err := os.MkdirAll(path, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", path, err)
		}
	}

	// Create .locks directory
	locksDir := filepath.Join(backlogDir, ".locks")
	if err := os.MkdirAll(locksDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", locksDir, err)
	}

	// Create config.yaml
	configPath := filepath.Join(backlogDir, "config.yaml")
	configContent := `# Backlog local configuration
# This file is auto-generated by 'backlog init'

version: 1

# Default settings for this backlog
defaults:
  # Default output format: table, json, plain, id-only
  format: table
`
	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}

	fmt.Println("Initialized backlog in .backlog/")
	return nil
}
